### ISSUE TITLE
Issue on build - Ubuntu 20, x86

### ISSUE THREAD

**Issue by bhaktatejas922** [microrealestate/microrealestate#159]
Really appreciate all of the hard work on this repo! 

I keep getting this issue when i do a build
```
  __  __   _                         ____                   _   _____         _             _          
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___ 
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|
                                                                                                       
The application designed to assist landlords in managing their properties and rentals

The REDIS_PORT variable is not set. Defaulting to a blank string.
The MONGO_PORT variable is not set. Defaulting to a blank string.
The LOGGER_LEVEL variable is not set. Defaulting to a blank string.
The GATEWAY_EXPOSE_FRONTENDS variable is not set. Defaulting to a blank string.
The AUTHENTICATOR_URL variable is not set. Defaulting to a blank string.
The API_URL variable is not set. Defaulting to a blank string.
The PDFGENERATOR_URL variable is not set. Defaulting to a blank string.
The LANDLORD_FRONTEND_URL variable is not set. Defaulting to a blank string.
The TENANT_FRONTEND_URL variable is not set. Defaulting to a blank string.
The TENANTAPI_URL variable is not set. Defaulting to a blank string.
The AUTHENTICATOR_PORT variable is not set. Defaulting to a blank string.
The REDIS_URL variable is not set. Defaulting to a blank string.
The EMAILER_URL variable is not set. Defaulting to a blank string.
The SIGNUP variable is not set. Defaulting to a blank string.
The PDFGENERATOR_PORT variable is not set. Defaulting to a blank string.
The UPLOAD_MAX_SIZE variable is not set. Defaulting to a blank string.
The EMAILER_PORT variable is not set. Defaulting to a blank string.
The APP_NAME variable is not set. Defaulting to a blank string.
The MAILGUN_API_KEY variable is not set. Defaulting to a blank string.
The MAILGUN_DOMAIN variable is not set. Defaulting to a blank string.
The SMTP_SERVER variable is not set. Defaulting to a blank string.
The SMTP_PORT variable is not set. Defaulting to a blank string.
The SMTP_SECURE variable is not set. Defaulting to a blank string.
The SMTP_USERNAME variable is not set. Defaulting to a blank string.
The SMTP_PASSWORD variable is not set. Defaulting to a blank string.
The API_PORT variable is not set. Defaulting to a blank string.
The TENANTAPI_PORT variable is not set. Defaulting to a blank string.
The LANDLORD_FRONTEND_PORT variable is not set. Defaulting to a blank string.
The DOCKER_GATEWAY_URL variable is not set. Defaulting to a blank string.
The TENANT_FRONTEND_PORT variable is not set. Defaulting to a blank string.
The Compose file './docker-compose.microservices.base.yml' is invalid because:
services.api.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.authenticator.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.emailer.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.landlord-frontend.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.mongo.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.pdfgenerator.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.redis.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tenant-frontend.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.tenantapi.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
1
➜  microrealestate git:(main) ✗

**Comment by bhaktatejas922** [comment]
also, tenant sign in doesnt seem to work with GMail

**Comment by camelaissani** [comment]
I've been working on #108 to simplify the install of the application. This will solve your problem soon :crossed_fingers: 
About the tenant app, the user has to be referenced with his email as a contact in one or many tenant contracts.

**Comment by camelaissani** [comment]
@bhaktatejas922 issue #108 has been fixed. Please follow the new installation procedure https://github.com/microrealestate/microrealestate#1-install-the-application. This should fix this issue.

**Comment by cdtzabra** [comment]
@camelaissani  HI

I came across the project today and wanted to try it out.
Unfortunately, the procedure doesn't work.
Same error when I try `./mre build`.
The `./mre` start doesn't work either, it tries to access the path `xxx/xx/services` which doesn't exist.

```shell
mkdir -p microrealestate; curl -L https://github.com/microrealestate/microrealestate/releases/latest/download/mre-linux-x64.tar.gz | tar -xz -C microrealestate

$ cd microrealestate
$ ./mre start
```

My workaround: make a git clone first and copy the ./mre binary into it

```shell
git clone https://github.com/microrealestate/microrealestate.git
cd microrealestate

mkdir -p microrealestate; curl -L https://github.com/microrealestate/microrealestate/releases/latest/download/mre-linux-x64.tar.gz | tar -xz -C microrealestate

mv microrealestate/mre .
rm -rf microrealestate

$ ./mre start

# I got this "invalid reference format" error from docker-compose
./mre showconfig # identified a typo error in the gateway service image name
# I got this "invalid reference format" error from docker-compose
```

**Comment by camelaissani** [comment]
@cdtzabra thank you for spotting the issue in the docker compose file. I just fixed it.

Anyway this regression was added after the release of version v1.0.0-alpha.1 and should not impact it.
From what you described I would say you fall in a situation where you ran the application with docker images built in dev mode.

Could you test again but first remove the cloned repository and second clean the existing containers and images?
Please adjust the docker commands to target only the mre containers/images. Here all containers and images will be removed.
```
rm -rf ./microrealestate
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

Next you can follow the install procedure:  https://github.com/microrealestate/microrealestate#1-install-the-application

**Comment by bhaktatejas922** [comment]
@camelaissani could you elaborate on the email issue? tenant sign in email doesnt seem to send with GMail

**Comment by cdtzabra** [comment]
Hi

@camelaissani 

cleanup done with  `docker-compose down --rmi all -v --remove-orphans`  


I followed the procedure and still have the same error.

```
~/Downloads$ mkdir -p microrealestate; curl -L https://github.com/microrealestate/microrealestate/releases/latest/download/mre-linux-x64.tar.gz | tar -xz -C microrealestate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25.5M  100 25.5M    0     0  8430k      0  0:00:03  0:00:03 --:--:-- 10.5M

~/Downloads$ cd microrealestate/
~/Downloads/microrealestate$ ls
backup  base.env  docker-compose.microservices.base.yml  docker-compose.microservices.prod.yml  mre
~/Downloads/microrealestate$ ./mre start



  __  __   _                         ____                   _   _____         _             _          
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___ 
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|
                                                                                                       
The application designed to assist landlords in managing their properties and rentals

? Do you want the database to be populated with? no data (keep existing data)
? Select your email delivery service? (required for password reset and tenant sign in) Gmail
? Enter your Gmail email address: myemail@gmail.com
? Enter your Gmail app password: [hidden]
? Enter the sender email address (from): myemail@gmail.com
? Enter the reply to email address (reply to): myemail@gmail.com
? Enter the URL to access the landlord front-end: http://localhost:8080/landlord
? Enter the URL to access the tenant front-end (it should share the same domain and port as the landlord front-end URL): http://localhost:8080/tenant

7: Pulling from library/mongo
Digest: sha256:3f765972fa2d1d0a748762ba43930f06f0c3ea58986582dd4663fe5ad7b63f0e
Status: Downloaded newer image for mongo:7
The UPLOAD_MAX_SIZE variable is not set. Defaulting to a blank string.
The MAILGUN_API_KEY variable is not set. Defaulting to a blank string.
The MAILGUN_DOMAIN variable is not set. Defaulting to a blank string.
The SMTP_SERVER variable is not set. Defaulting to a blank string.
The SMTP_PORT variable is not set. Defaulting to a blank string.
The SMTP_SECURE variable is not set. Defaulting to a blank string.
The SMTP_USERNAME variable is not set. Defaulting to a blank string.
The SMTP_PASSWORD variable is not set. Defaulting to a blank string.
Creating network "microrealestate_net" with driver "bridge"
Pulling mongo (mongo:7)...
Building pdfgenerator
ERROR: could not find /home/myuser/Downloads/microrealestate/services/pdfgenerator: stat /home/myuser/Downloads/microrealestate/services/pdfgenerator: no such file or directory
Service 'pdfgenerator' failed to build : Build failed
1
```

**Comment by camelaissani** [comment]
@bhaktatejas922 Have you been able to run the application with the new procedure?
Have you answer the prompts to set the gmail info? (You can check that in the `.env `file)
Have you been able to create an account (signup) in the landlord application?
Have you created a tenant with a contact email ? This email will be used to connect in the tenant app.

**Comment by mzzntn** [comment]
Hi @camelaissani 

I was able to test the latest installation guide. Unfortunately, I still receive the same error

`The UPLOAD_MAX_SIZE variable is not set. Defaulting to a blank string.
The GMAIL_EMAIL variable is not set. Defaulting to a blank string.
The GMAIL_APP_PASSWORD variable is not set. Defaulting to a blank string.
The MAILGUN_API_KEY variable is not set. Defaulting to a blank string.
The MAILGUN_DOMAIN variable is not set. Defaulting to a blank string.
The SMTP_SERVER variable is not set. Defaulting to a blank string.
The SMTP_PORT variable is not set. Defaulting to a blank string.
The SMTP_SECURE variable is not set. Defaulting to a blank string.
The SMTP_USERNAME variable is not set. Defaulting to a blank string.
The SMTP_PASSWORD variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 395, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 395, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
1
`

**Comment by camelaissani** [comment]
This might help: https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version

**Comment by julusalas21** [comment]
In my experience, docker-compose was the wrong version for me. I updated docker-compose from 1.25.x to 1.27.x and the application was able to start properly.

**Comment by camelaissani** [comment]
No need to build anymore with the new install procedure.
I'll close this issue. Please reopen if it is still a problem.
