### ISSUE TITLE
Simplify the self hosting procedure

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#200]
Just run docker compose command to run the application on a local machine or on a private server

**Comment by flowe14** [comment]
Do you have a working docker compose I can ,when I install can login to create new account.

**Comment by camelaissani** [comment]
@flowe14 there is still some dev/doc to do but you can test my latest changes.

### Download docker compose file

```
curl https://raw.githubusercontent.com/microrealestate/microrealestate/master/docker-compose.yml > docker-compose.yml
```

### Local machine deployment

```
docker compose --profile local up
```

App accessible on
http://localhost:8080/landlord
http://localhost:8080/tenant

### Private machine deployment using a domain

```
sudo APP_PROTOCOL=https APP_DOMAIN=app.example.com docker compose up
```
Make sure your DNS points to the server. The app will automatically issue the ssl certs.

App accessible on:
https://app.example.com/landlord
https://app.example.com/tenant

**Comment by camelaissani** [comment]
@flowe14 I need more info to understand what's wrong.

- Do you run the app under a domain or on localhost?
- Have you downloaded the compose file in an empty directory? A .env file in the same directory might cause some problems.
- Have you stopped all the previous containers before starting the app? You might want to cleanup the previous docker images/containers (docker system prune).
- Do you have any logs from the browser console?

**Comment by flowe14** [comment]
I tried both methods local and with domain.
I used a new Vm with only docker installed
I didn't put a env file in the directory.
No logs from web browser 
It seems as if it can't create the first account.

**Comment by flowe14** [comment]
I tried both methods local and with domain.
I used a new Vm with only docker installed
I didn't put a env file in the directory.
No logs from web browser 
It seems as if it can't create the first account.

**Comment by camelaissani** [comment]
Any logs from the terminal when running the docker compose command?

**Comment by flowe14** [comment]
![Screenshot 2024-10-21 124258 png-gateway error](https://github.com/user-attachments/assets/4f4cb0da-e221-4e77-955d-9b9c31475e31)
please see error for one of the container

**Comment by camelaissani** [comment]
I just pushed a fix. Could you download again the `docker-compose.yml`  and retry to run the application?

**Comment by flowe14** [comment]
I deploy a new vm and download the new compose file still cant create the first user still giving signing error.

![image](https://github.com/user-attachments/assets/7d479a4f-9efa-4e96-ac2d-fb20e3d03267)

**Comment by camelaissani** [comment]
Now it looks like all services are running.

Do you have any logs in the browser console?

**Comment by flowe14** [comment]
all the applications seem to be running but i can't create the first account to login application.

The error i get is Something went wrong no other log in web browser.

**Comment by camelaissani** [comment]
On this page you can find more information of what I meant about the browser console https://snov.io/knowledgebase/how-to-open-console-or-network-details-in-your-browser/

I try to figure out if the signup http call is done properly. I suspect the request is not able to reach the server.

Can you see ok in the browser if you type this url in your browser https://app.example.com/health ?

Replace app.example.com above by your domain 
(I assume you're running the app with your domain in https).

**Comment by flowe14** [comment]
I think the application is working but i must access using localhost or else i will get denied as you can see below.

is there a way i can install on a remote server  and access using ip address or run it through cloudflare tunnel

signin:1 Access to XMLHttpRequest at 'http://localhost:8080/api/v2/authenticator/landlord/signin' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by camelaissani** [comment]
Could you try the last version?

I guess starting the app by using the ip server will help:

```
sudo APP_DOMAIN=x.x.x.x docker compose up
```
x.x.x.x the ip address of your server

**Comment by flowe14** [comment]
i will try that and see if it work using the ip address, can i also run the application Cloudflare tunnel.

Thank you for your help

**Comment by camelaissani** [comment]
After checking what is Cloudflare tunnel, I think you need to adapt the docker-compose.yml file.

The GATEWAY_URL should be replaced with the url provided by Cloudflare.
Same for LANDLORD_APP_URL and TENANT_APP_URL.

Let's say that Cloudflare tunnel gives you this url: https://myapp.mytunnel.com

The env should be set as the following:

GATEWAY_URL=https://myapp.mytunnel.com
LANDLORD_APP_URL=https://myapp.mytunnel.com/landlord 
TENANT_APP_URL=https://myapp.mytunnel.com/tenant
